### ISSUE TITLE
bin/grunt-remove-logging cli error

### ISSUE THREAD

**Issue by btakita** [ehynds/grunt-remove-logging#26]
```
require("grunt").npmTasks("grunt-remove-logging").cli();
                 ^
TypeError: Object #<Object> has no method 'npmTasks'
    at Object.<anonymous> (node_modules/grunt-remove-logging/bin/grunt-remove-logging:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by adrozdov-okta** [comment]
npmTakss was removed. Check out the discussion in this issue: https://github.com/gruntjs/grunt/issues/438
